# General settings
title: Arun Frey
title_html: "<b>Ar</b>un<b><span class=\"invisible\"> </span>Frey</b>"
description:
  en: Arun Frey is a PhD student in sociology...
baseurl: ""
url: "https://arunfrey.github.io"


# Author
author: Arun Frey

email: arun.frey@sociology.ox.ac.uk
twitter_username: ArunFrey
github_username: ArunFrey
#curriculum:
#  url: assets/CV_AFrey.pdf

# Nav menu
nav_ext_links:
  - name: Blog
    url:
      fr: https://sociologs.com/fr/
      en: https://sociologs.com/en/

# Piwik
piwik:
  url: batcloud.me/piwik
  site_id: 2

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data"]
theme: academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock